/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : bigint,
  'icon' : string,
  'name' : string,
  'budgetLimit' : [] | [number],
  'isDefault' : boolean,
}
export interface CategoryTotal {
  'categoryId' : bigint,
  'total' : number,
  'categoryName' : string,
  'budgetLimit' : [] | [number],
}
export interface Expense {
  'id' : bigint,
  'categoryId' : bigint,
  'month' : bigint,
  'title' : string,
  'isRecurring' : boolean,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'year' : bigint,
  'notes' : string,
  'amount' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[string, string, [] | [number]], bigint>,
  'addExpense' : ActorMethod<
    [string, number, bigint, bigint, bigint, string, boolean],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteExpense' : ActorMethod<[bigint], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getBudgetAlerts' : ActorMethod<[bigint, bigint], Array<CategoryTotal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryTotals' : ActorMethod<[bigint, bigint], Array<CategoryTotal>>,
  'getExpensesByMonth' : ActorMethod<[bigint, bigint], Array<Expense>>,
  'getMonthlyTotal' : ActorMethod<[bigint, bigint], number>,
  'getRecurringExpenses' : ActorMethod<[], Array<Expense>>,
  'getTopSpendingCategories' : ActorMethod<
    [bigint, bigint],
    Array<CategoryTotal>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCategory' : ActorMethod<
    [bigint, string, string, [] | [number]],
    undefined
  >,
  'updateExpense' : ActorMethod<
    [bigint, string, number, bigint, bigint, bigint, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];