/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'budgetLimit' : IDL.Opt(IDL.Float64),
  'isDefault' : IDL.Bool,
});
export const CategoryTotal = IDL.Record({
  'categoryId' : IDL.Nat,
  'total' : IDL.Float64,
  'categoryName' : IDL.Text,
  'budgetLimit' : IDL.Opt(IDL.Float64),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'month' : IDL.Nat,
  'title' : IDL.Text,
  'isRecurring' : IDL.Bool,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'year' : IDL.Nat,
  'notes' : IDL.Text,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Float64)],
      [IDL.Nat],
      [],
    ),
  'addExpense' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getBudgetAlerts' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(CategoryTotal)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryTotals' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(CategoryTotal)],
      ['query'],
    ),
  'getExpensesByMonth' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'getMonthlyTotal' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Float64], ['query']),
  'getRecurringExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getTopSpendingCategories' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(CategoryTotal)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCategory' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Float64)],
      [],
      [],
    ),
  'updateExpense' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'budgetLimit' : IDL.Opt(IDL.Float64),
    'isDefault' : IDL.Bool,
  });
  const CategoryTotal = IDL.Record({
    'categoryId' : IDL.Nat,
    'total' : IDL.Float64,
    'categoryName' : IDL.Text,
    'budgetLimit' : IDL.Opt(IDL.Float64),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'month' : IDL.Nat,
    'title' : IDL.Text,
    'isRecurring' : IDL.Bool,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'year' : IDL.Nat,
    'notes' : IDL.Text,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Float64)],
        [IDL.Nat],
        [],
      ),
    'addExpense' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getBudgetAlerts' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(CategoryTotal)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryTotals' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(CategoryTotal)],
        ['query'],
      ),
    'getExpensesByMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getMonthlyTotal' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Float64], ['query']),
    'getRecurringExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getTopSpendingCategories' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(CategoryTotal)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCategory' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Float64)],
        [],
        [],
      ),
    'updateExpense' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };